### ISSUE TITLE
Не запускается на Windows 7 x64

### ISSUE THREAD

**Issue by kda2495** [amnezia-vpn/amneziawg-windows-client#11]
После установки .msi файла, и при запуске AmneziaWG на Windows 7 x64 ничего не происходит.

**Comment by a0346f102085fe9f** [comment]
Патчер помогает https://github.com/stunndard/golangwin7patch

**Comment by kda2495** [comment]
> Патчер помогает https://github.com/stunndard/golangwin7patch

Спасибо, все заработало. Но не мешало бы сам msi пропатчить тоже, если так можно.

**Comment by MarkizFireFox** [comment]
> Патчер помогает https://github.com/stunndard/golangwin7patch

А как использовать это? Разобраться не могу

**Comment by kda2495** [comment]
> > Патчер помогает https://github.com/stunndard/golangwin7patch
> 
> А как использовать это? Разобраться не могу

Запускаете программу, нажимаете Open, идете по пути C:\Program Files\AmneziaWG и выбираете AmneziaWG.exe

**Comment by MarkizFireFox** [comment]
> > > Патчер помогает https://github.com/stunndard/golangwin7patch
> > 
> > 
> > А как использовать это? Разобраться не могу
> 
> Запускаете программу, нажимаете Open, идете по пути C:\Program Files\AmneziaWG и выбираете AmneziaWG.exe

да не, пропатчить систему как? типа архив скачал, а дальше что?

**Comment by iRadioMan** [comment]
Вы бы еще на WinXP пытались запустить)) Ахах

**Comment by Bluetrys** [comment]
> > > Патчер помогает https://github.com/stunndard/golangwin7patch
> > 
> > 
> > А как использовать это? Разобраться не могу
> 
> Запускаете программу, нажимаете Open, идете по пути C:\Program Files\AmneziaWG и выбираете AmneziaWG.exe

вопрос
как запустить программу
там сплошные файлы

**Comment by BloodMesa** [comment]
> > > > Патчер помогает https://github.com/stunndard/golangwin7patch
> > > 
> > > 
> > > А как использовать это? Разобраться не могу
> > 
> > 
> > Запускаете программу, нажимаете Open, идете по пути C:\Program Files\AmneziaWG и выбираете AmneziaWG.exe
> 
> вопрос как запустить программу там сплошные файлы

Ищи справа слово Releases, там нажми на 0.2 и там скачай экзешник

**Comment by DesignBun** [comment]
> Патчер помогает https://github.com/stunndard/golangwin7patch

НА виндовс 7 х86 после патча все равно не запускается

**Comment by londtreeforce** [comment]
у меня на вин10 перестала запускаться, процесс появляется и сразу пропадает..

**Comment by GreenKta** [comment]
> Пробуйте https://github.com/spvkgn/amneziawg-windows-client/releases/tag/1.0.0-win7

Здравствуйте! Подскажите, пожалуйста, что делать - версия по ссылке рабочая, и прекрасно запускается на Семёрке, но проблема в том, что со мной поделились ключом для подключения, а программа просит туннель из файла. 

Спасибо!

**Comment by BloodMesa** [comment]
> > Пробуйте https://github.com/spvkgn/amneziawg-windows-client/releases/tag/1.0.0-win7
> 
> Здравствуйте! Подскажите, пожалуйста, что делать - версия по ссылке рабочая, и прекрасно запускается на Семёрке, но проблема в том, что со мной поделились ключом для подключения, а программа просит туннель из файла.
> 
> Спасибо!

Ищи в гугле, как сделать warp файл для амнезии

**Comment by GreenKta** [comment]
> > > Пробуйте https://github.com/spvkgn/amneziawg-windows-client/releases/tag/1.0.0-win7
> > 
> > 
> > Здравствуйте! Подскажите, пожалуйста, что делать - версия по ссылке рабочая, и прекрасно запускается на Семёрке, но проблема в том, что со мной поделились ключом для подключения, а программа просит туннель из файла.
> > Спасибо!
> 
> Ищи в гугле, как сделать warp файл для амнезии

Благодарю вас, что мимо не прошли!

Загуглила. Выкачала себе образец файла формата .conf, но вопрос остаётся - как мне эту vless:// ссылку запихнуть в файл формата .conf? Я, к сожалению, с кодами никак, гугл "vless to conf" тоже ничего не выдал, истоптала много сайтов и решения, чтобы человек на уровне "этот кусок кода явно идёт сюда, а этот вот сюда" сам справился с комировать-вставить - не нашла. По образцу я бы и IP выдернула, и прочие параметры из vless этого, два файла вот, на лапах лежат, а что с ними делать - без понятия. Может, конвертер какой есть? Спасибо.

**Comment by kda2495** [comment]
> > > > Пробуйте https://github.com/spvkgn/amneziawg-windows-client/releases/tag/1.0.0-win7
> > > 
> > > 
> > > Здравствуйте! Подскажите, пожалуйста, что делать - версия по ссылке рабочая, и прекрасно запускается на Семёрке, но проблема в том, что со мной поделились ключом для подключения, а программа просит туннель из файла.
> > > Спасибо!
> > 
> > 
> > Ищи в гугле, как сделать warp файл для амнезии
> 
> Благодарю вас, что мимо не прошли!
> 
> Загуглила. Выкачала себе образец файла формата .conf, но вопрос остаётся - как мне эту vless:// ссылку запихнуть в файл формата .conf? Я, к сожалению, с кодами никак, гугл "vless to conf" тоже ничего не выдал, истоптала много сайтов и решения, чтобы человек на уровне "этот кусок кода явно идёт сюда, а этот вот сюда" сам справился с комировать-вставить - не нашла. По образцу я бы и IP выдернула, и прочие параметры из vless этого, два файла вот, на лапах лежат, а что с ними делать - без понятия. Может, конвертер какой есть? Спасибо.

https://github.com/ImMALWARE/bash-warp-generator
Попробуйте этот проект, в описании все указано сделайте себе конфиг КВН и пользуйтесь!

**Comment by Zauberer2** [comment]
> Пробуйте https://github.com/spvkgn/amneziawg-windows-client/releases/tag/1.0.0-win7

Вы можете сделать дистрибутив win7 для последней версии amneziawg?

**Comment by spvkgn** [comment]
@Zauberer2 https://github.com/spvkgn/amneziawg-windows-client/releases/tag/2.0.0-win7

**Comment by tdok57** [comment]
> [@Zauberer2](https://github.com/Zauberer2) https://github.com/spvkgn/amneziawg-windows-client/releases/tag/2.0.0-win7

что делать, если при запуске ничего не происходит? на виндовс 7

**Comment by Ykat-gitch** [comment]
> [@Zauberer2](https://github.com/Zauberer2) https://github.com/spvkgn/amneziawg-windows-client/releases/tag/2.0.0-win7

All good, but .. 

<img width="1376" height="877" alt="Image" src="https://github.com/user-attachments/assets/a9dba483-a1c8-4db6-b8f5-fb0ab02a6bcd" />

**Comment by PankerSergey** [comment]
> [@Zauberer2](https://github.com/Zauberer2) https://github.com/spvkgn/amneziawg-windows-client/releases/tag/2.0.0-win7

Огромная Благодарность. Спустя час я наконец-то запустил Амнезию на своей старенькой 7ке)) Устал мучаться от сервиса в Happ, который не то на компе (тут-то уже давно) уже даже на телефоне стало использовать очень дорого по нервас...

**Comment by DLLHostExe** [comment]
> [@Zauberer2](https://github.com/Zauberer2) https://github.com/spvkgn/amneziawg-windows-client/releases/tag/2.0.0-win7

не знаю может я что то делаю не так, но при попытке запуска просто тишина. .exe я закинул в папку и просто ее пытался запустить. и изначальная от MSI инсталятора не запускается тоже

upd: проблема с запуском решилась после патча через https://github.com/stunndard/golangwin7patch
