### ISSUE TITLE
Installer doesn't work

### ISSUE THREAD

**Issue by Kit-mudylo** [amnezia-vpn/amneziawg-windows-client#13]
After I launch it, a window appears for a half a second, then disappears.

Antivirus and brandmauer turned off.

**Comment by kda2495** [comment]
> After I launch it, a window appears for a half a second, then disappears.
> 
> Antivirus and brandmauer turned off.

What system do you have?

**Comment by Kit-mudylo** [comment]
Windows 10 x64

Also I think it'll be worth to say, that I already downloaded it before, but had to reinstall it

**Comment by Kit-mudylo** [comment]
I've just deleted amneziawg in "programs" tab in settings and installer worked.

I forgot that feature exist, lol.
